mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: test2.test2.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://x:x/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: x
    password: x
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true

# redis集群
  redis:
    cluster:
      nodes: x:x,x:x,x:x,x:x,x:x,x:x
    password: x


# 单个redis服务
#  redis:
#    database: 0
#    host: x
#    port: x
#    password: x
#    timeout: 60000
#    jedis:
#      pool:
#        max-wait: 1
#        max-active: 8
#        max-idle: 8
#        min-idle: 0

